In [31]:
from src.NSMFermions.fermi_hubbard_library import build_mask_mapping,_adag_adag_a_a_loop_numba_with_dict
from src.NSMFermions.hamiltonian_utils import FermiHubbardHamiltonian
import numpy as np

In [33]:
FHH=FermiHubbardHamiltonian(4,0,2,0,)


In [35]:
print(FHH.basis)
m,mask2index=build_mask_mapping(FHH.basis)
print(m)

prefix_sums = np.cumsum(FHH.basis, axis=1)
prefix_sums = np.hstack([np.zeros((FHH.basis.shape[0], 1), dtype=prefix_sums.dtype),
                         prefix_sums[:, :-1]])

[[1 1 0 0]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 0 1 1]]
[ 3  5  9  6 10 12]


0

In [36]:
print(prefix_sums)

[[0 1 2 2]
 [0 1 1 2]
 [0 1 1 1]
 [0 0 1 2]
 [0 0 1 1]
 [0 0 0 1]]


In [ ]:
print(FHH.adag_adag_a_a_matrix(2,3,0,1).tocsr())
print(FHH.adag_adag_a_a_matrix(3,2,0,1).tocsr())


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (6, 6)>
  Coords	Values
  (5, 0)	-1.0


AttributeError: 'tuple' object has no attribute 'tocsr'