# How to deal with a Nuclear Shell Model (NSM) Hamiltonian -a funny guide to madness-

NSM Hamiltonians are many-body Hamiltonians represented in a single particle framework (or nucleon modes) described by Valence orbitals (with the famous set of quantum numbers that describe the 3D harmonic oscillator $|n,l,j,m,t,t_z\rangle$. The last two quantum numbers describe the isospin of the nucleons (proton or neutron).

First of all, we need to commit: we need to decide which Valence shell we are going to use. This choice translates in selecting the proper "nuclear_interaction.txt" file related to the correspoding valence shell.

- p shell --> 'data/cki' file 
- sd shell --> 'data/usdb.nat' file 
- pf shell --> 'data/gxpf1a' file 

Don't worry about these names, for you these simply are file text with matrix entries that are going to be the parameters of your NSM Hamiltonian:
$$
H=\sum_a c^{+}_a c_a + \frac{1}{4}\sum_{abcd} v_{abdc} c^{+}_a c^{+}_b c_c c_d.
$$

Ok, too much verbose, let's start with the Imports

In [1]:
from src.NSMFermions.hamiltonian_utils import FermiHubbardHamiltonian # the many-body Hamiltonian class
from src.NSMFermions.nuclear_physics_utils import SingleParticleState,J2operator,get_twobody_nuclearshell_model # routines and class useful for the nuclear part
import scipy # just scipy, easy, no?
import numpy as np 
import matplotlib.pyplot as plt # to plot things

/home/ecosta/miniconda3/envs/quantum_annealing_nsm/lib/python3.10/site-packages/tqdm_joblib/__init__.py:4: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm


We initialize the Single Particle State class with the corresponding file text. We also initialize the number of proton neutron and the corresponding number of modes for each nucleon

In [2]:
file_name='data/usdb.nat'

SPS=SingleParticleState(file_name=file_name)
# single particle energies
print('single particle energies=',SPS.energies,'\n')
print('mapping between nucleon modes a and the quantum numbers',SPS.state_encoding)

nucleon_modes_per_isospin=SPS.energies.shape[0]//2 # we are counting per species. I know, we need a .num_modes attribute

num_neutrons=2
num_protons=2

single particle energies= [-3.9257 -3.9257 -3.9257 -3.9257 -3.9257 -3.9257 -3.2079 -3.2079  2.1117
  2.1117  2.1117  2.1117 -3.9257 -3.9257 -3.9257 -3.9257 -3.9257 -3.9257
 -3.2079 -3.2079  2.1117  2.1117  2.1117  2.1117] 

mapping between nucleon modes a and the quantum numbers [(0, 2, 2.5, np.float64(-2.5), 0.5, 0.5), (0, 2, 2.5, np.float64(-1.5), 0.5, 0.5), (0, 2, 2.5, np.float64(-0.5), 0.5, 0.5), (0, 2, 2.5, np.float64(0.5), 0.5, 0.5), (0, 2, 2.5, np.float64(1.5), 0.5, 0.5), (0, 2, 2.5, np.float64(2.5), 0.5, 0.5), (1, 0, 0.5, np.float64(-0.5), 0.5, 0.5), (1, 0, 0.5, np.float64(0.5), 0.5, 0.5), (0, 2, 1.5, np.float64(-1.5), 0.5, 0.5), (0, 2, 1.5, np.float64(-0.5), 0.5, 0.5), (0, 2, 1.5, np.float64(0.5), 0.5, 0.5), (0, 2, 1.5, np.float64(1.5), 0.5, 0.5), (0, 2, 2.5, np.float64(-2.5), 0.5, -0.5), (0, 2, 2.5, np.float64(-1.5), 0.5, -0.5), (0, 2, 2.5, np.float64(-0.5), 0.5, -0.5), (0, 2, 2.5, np.float64(0.5), 0.5, -0.5), (0, 2, 2.5, np.float64(1.5), 0.5, -0.5), (0, 2, 2.5, np.float64(2.

Now, we can initialize the NSM Hamiltonian and look at the many-body basis. It is a tensor with the first index as the many-body basis index and second index the corresponding nucleon modes in the tensor product basis state

In [3]:
NSMHamiltonian=FermiHubbardHamiltonian(size_a=nucleon_modes_per_isospin,size_b=nucleon_modes_per_isospin,nparticles_a=num_neutrons,nparticles_b=num_protons,symmetries=[SPS.total_M_zero]) # the symmetry that we need is the M=0 condition, if we do not add anything we get the full many-body basis

print(NSMHamiltonian.basis)


[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 1]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]


/home/ecosta/miniconda3/envs/quantum_annealing_nsm/lib/python3.10/site-packages/numba/typed/typeddict.py:39: NumbaTypeSafetyWarning: unsafe cast from int64 to uint64. Precision may be lost.
  return d[key]


Now we initialize the NSM Hamiltonian, starting from the external potential $\sum_a e_a c^{+}_a c_a$

In [4]:
NSMHamiltonian.get_external_potential(external_potential=SPS.energies)

Then we go to the two-body term, loading the matrix dict

In [5]:
print(SPS.state_encoding[19],SPS.state_encoding[2],SPS.state_encoding[1],SPS.state_encoding[16])



(1, 0, 0.5, np.float64(0.5), 0.5, -0.5) (0, 2, 2.5, np.float64(-0.5), 0.5, 0.5) (0, 2, 2.5, np.float64(-1.5), 0.5, 0.5) (0, 2, 2.5, np.float64(1.5), 0.5, -0.5)


In [ ]:
twobody_dict,_=get_twobody_nuclearshell_model(file_name=file_name)


Computing the matrix, pls wait... (u_u) 



100%|██████████| 24/24 [00:47<00:00,  1.98s/it]

Starting 16496 two-body terms...


Two-body terms: 100%|██████████| 16496/16496 [00:02<00:00, 7455.91it/s]
Two-body interaction matrix completed.


In [ ]:

NSMHamiltonian.get_twobody_interaction_optimized(twobody_dict)



16496it [01:22, 199.16it/s]


In order to use the hamiltonian, we need to compute the full Hamiltonian matrix, using get_hamiltonian()

In [7]:
NSMHamiltonian.get_hamiltonian()

In [11]:
print(NSMHamiltonian.twobody_operator)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 54110 stored elements and shape (640, 640)>
  Coords	Values
  (0, 0)	-5.934974603174604
  (0, 1)	2.1441927358413584
  (0, 2)	-0.10915079365079428
  (0, 3)	-0.6398020847719197
  (0, 4)	0.3682345247093515
  (0, 5)	0.5211067201086399
  (0, 6)	-0.9690507936507938
  (0, 7)	0.22802569399122857
  (0, 9)	-0.632878191158204
  (0, 10)	0.45225308401658526
  (0, 11)	0.2665777205429144
  (0, 12)	-1.2129704215656378
  (0, 15)	-0.5542253968253976
  (0, 16)	0.43082268503532073
  (0, 20)	0.03468810059641142
  (0, 21)	0.2890940607855491
  (0, 22)	-0.2239312965819814
  (0, 26)	-0.45876507936507965
  (0, 27)	0.4680380952380956
  (0, 34)	1.096283198521862
  (0, 40)	-0.3682345247093515
  (0, 41)	0.19362401723902906
  (0, 42)	-0.5858860751129027
  (0, 43)	-0.04349146264472342
  (0, 44)	-0.2665777205429144
  :	:
  (639, 591)	-0.39534000000000014
  (639, 599)	0.46263760950344823
  (639, 600)	-0.4744024744405058
  (639, 603)	0.37221387999358563
  (63

At this point, getting the spectrum is easy as getting the empadronamiento in Barcelona (joke)

In [8]:
egs,psigs=NSMHamiltonian.get_spectrum(n_states=1) #we are only interested in the gs 

print(f'energy ground state={egs[0]:.5} Mev \n')


energy ground state=-15.703 Mev 



We can also play with other attributes that the Hamiltonian can provide, such as 2-body operators $T_{ab}^{cd}=c^{+}_a c^{+}_{b} c_c c_d$

In [20]:
t_0312=NSMHamiltonian.adag_adag_a_a_matrix(0,3,1,2) # it's a matrix in the many-body basis

# we compute the expectation value using Scipy <psi| T_01^23 |psi>
expectation_value=psigs[:,0].conjugate().dot(t_0312.dot(psigs[:,0])) # the 0 index is because  psigs \in [dim(Hilbert space),n_states]
print('expectation value=',expectation_value)

expectation value= 0.19708205121236266


To call the Hamiltonian we simply use

In [ ]:
print(NSMHamiltonian.hamiltonian)