In [3]:

from src.hamiltonian_utils import FermiHubbardHamiltonian
from src.nuclear_physics_utils import get_twobody_nuclearshell_model,SingleParticleState,QuadrupoleOperator,J2operator
import numpy as np
import torch
from typing import Dict
import scipy
from src.qml_models import AdaptVQEFermiHubbard
from src.qml_utils.train import Fit
from src.qml_utils.utils import configuration
from scipy.sparse.linalg import eigsh,expm_multiply
from tqdm import trange
import matplotlib.pyplot as plt

from scipy.sparse import lil_matrix
file_name='data/usdb.nat'

SPS=SingleParticleState(file_name=file_name)

nparticles_a=2
nparticles_b=2

size_a=SPS.energies.shape[0]//2
size_b=SPS.energies.shape[0]//2

title=r'$^{18}$O'

In [4]:

# Compute the J^2 value
#J2Class=J2operator(size_a=size_a,size_b=size_b,nparticles_a=nparticles_a,nparticles_b=nparticles_b,single_particle_states=SPS.state_encoding,j_square_filename=file_name+'_j2',symmetries=[SPS.total_M_zero])

#Quadrupole Operator


# compute the NSM Hamiltonian
NSMHamiltonian=FermiHubbardHamiltonian(size_a=size_a,size_b=size_b,nparticles_a=nparticles_a,nparticles_b=nparticles_b,symmetries=[SPS.total_M_zero])
print('size=',size_a+size_b,size_b)
NSMHamiltonian.get_external_potential(external_potential=SPS.energies[:size_a+size_b])
twobody_matrix,energies=get_twobody_nuclearshell_model(file_name=file_name)

NSMHamiltonian.get_twobody_interaction(twobody_dict=twobody_matrix)

NSMHamiltonian.get_hamiltonian()

egs,psi0=NSMHamiltonian.get_spectrum(n_states=1)

print(egs)
print(NSMHamiltonian.basis)
print(NSMHamiltonian.hamiltonian)
print('total_m=',SPS.compute_m_exp_value(psi=psi0,basis=NSMHamiltonian.basis))

size= 24 12
Computing the matrix, pls wait... (u_u) 



100%|██████████| 24/24 [01:11<00:00,  2.98s/it]
16496it [01:22, 198.88it/s]


[-41.39649007]
[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 1]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
  (0, 0)	-21.637774603174606
  (0, 1)	2.1441927358413584
  (0, 2)	-0.10915079365079428
  (0, 3)	-0.6398020847719197
  (0, 4)	0.3682345247093515
  (0, 5)	0.5211067201086399
  (0, 6)	-0.9690507936507938
  (0, 7)	0.22802569399122857
  (0, 9)	-0.632878191158204
  (0, 10)	0.45225308401658526
  (0, 11)	0.2665777205429144
  (0, 12)	-1.2129704215656378
  (0, 15)	-0.5542253968253976
  (0, 16)	0.43082268503532073
  (0, 20)	0.03468810059641142
  (0, 21)	0.2890940607855491
  (0, 22)	-0.2239312965819814
  (0, 26)	-0.45876507936507965
  (0, 27)	0.4680380952380956
  (0, 34)	1.096283198521862
  (0, 40)	-0.3682345247093515
  (0, 41)	0.19362401723902906
  (0, 42)	-0.5858860751129027
  (0, 43)	-0.04349146264472342
  (0, 44)	-0.2665777205429144
  :	:
  (639, 591)	-0.39534000000000014
  (639, 599)	0.46263760950344823
  (639, 600)	-0.4744024744405058
  (639, 603)	0.372213879